# mot de taille inferieur à 5
L1 = ['jura', 'mari', 'pôle', 'bain', 'lié', 'roc', 'boum', 'pain', 'tout', 'boys', 'ri', 'vêtu', 'las', 'nés', 'suie', 'zèle', 'bave', 'brut', 'pins', 'mât', 'Lima', 'axée', 'Park', 'fiat', 'elle', 'âpre', 'tas', 'fées', 'bord', 'tare', 'perm', 'vise', 'âgé', 'gus', 'vu', 'parc', 'pro', 'taxi', 'pots', 'face', 'valu', 'cap', 'an', 'loue', 'serf', 'moi', 'jugé', 'frai', 'us', 'muet', 'soi', 'tons', 'cuve', 'roux', 'oh', 'gogo', 'daté', 'rive', 'rase', 'gril', 'mali', 'chou', 'clés', 'rôle', 'ais', 'acul', 'fêlé', 'rêne', 'fiel', 'ceci', 'Suzy', 'dort', 'joué', 'Nice', 'tien', 'fine', 'Karl', 'salé', 'payé', 'mais', 'via', 'fit', 'shah', 'lime', 'pied', 'ténu', 'bus', 'sen', 'han', 'cède', 'baie', 'hier', 'mêlé', 'ont', 'cal', 'hôte', 'cris', 'boue', 'menu', 'rapt']

# mot de taille égale à 5
L5 = ['prêté', 'mètre', 'roule', 'quant', 'Libye', 'ravin', 'gâter', 'valet', 'forer', 'ponts', 'lions', 'sauvé', 'raide', 'colle', 'école', 'déchu', 'livre', 'ligue', 'rebut', 'râler', 'vient', 'iront', 'doser', 'gibet', 'talus', 'mules', 'sabir', 'périr', 'gêner', 'salin', 'faces', 'serge', 'vente', 'gares', 'purin', 'avoir', 'coûts', 'anges', 'vents', 'plage', 'virer', 'choir', 'style', 'danse', 'gosse', 'enflé', 'régis', 'front', 'lâché', 'goulu', 'Rouen', 'hutte', 'pitié', 'séide', 'trois', 'volet', 'peste', 'argot', 'zones', 'gains', 'baron', 'roman', 'pures', 'shoot', 'nièce', 'rites', 'savon', 'évité', 'range', 'gerbe', 'haler', 'pique', 'clans', 'nouer', 'flots', 'files', 'Raoul', 'barde', 'volée', 'média', 'reçus', 'parus', 'vache', 'Start', 'nôtre', 'démis', 'entré', 'après', 'gifle', 'tuent', 'purge', 'copie', 'diane', 'ville', 'thune', 'nonne', 'balte', 'prévu', 'garce', 'hibou']

# mot de taille égale à 6
L6 = ['meneur', 'connut', 'affamé', 'angine', 'énorme', 'requis', 'cruche', 'bonnes', 'châsse', 'étudie', 'adapté', 'naquit', 'rasoir', 'étalon', 'ravage', 'retire', 'revers', 'compte', 'couard', 'Kaboul', 'pavage', 'Seguin', 'carnet', 'bottes', 'clergé', 'ramper', 'timbre', 'rougir', 'ferons', 'promis', 'vaille', 'abasie', 'trappe', 'confit', 'chipie', 'lézard', 'diable', 'nommer', 'finaud', 'conter', 'détenu', 'vessie', 'promet', 'répète', 'massif', 'arrhes', 'ouvrir', 'publia', 'venons', 'commun', 'bélier', 'marron', 'format', 'clarté', 'bloqué', 'envier', 'argent', 'garnir', 'muséum', 'restés', 'fouler', 'aboyer', 'radier', 'import', 'abordé', 'piqûre', 'mâcher', 'bêtise', 'brûler', 'report', 'blindé', 'cavité', 'flèche', 'tinter', 'amical', 'voulez', 'dragon', 'ciment', 'Lionel', 'équité', 'solide', 'opérer', 'Nantes', 'agréer', 'office', 'suivis', 'leçons', 'vérole', 'clouer', 'divine', 'veston', 'poncif', 'lapsus', 'dépend', 'bagage', 'rocher', 'truqué', 'glaçon', 'avides', 'résumé']

# mot de taille égale à 7
L7 = ['sphères', 'leaders', 'lexical', 'touchés', 'affreux', 'ouvrage', 'Quimper', 'refrain', 'réformé', 'usinage', 'courent', 'tiendra', 'risquer', 'service', 'précise', 'toxique', 'salades', 'trinité', 'exhaler', 'janvier', 'arguant', 'assurer', 'débâcle', 'lavette', 'couvert', 'esprits', 'troquer', 'ouverts', 'basculé', 'réunies', 'signant', 'filtrer', 'claquer', 'avances', 'étendue', 'mémoire', 'décidés', 'infamie', 'théâtre', 'bonasse', 'tailles', 'avertir', 'embryon', 'annuels', 'maîtres', 'martine', 'flairer', 'pleines', 'feinter', 'chichis', 'franche', 'fourrer', 'polluer', 'alléger', 'housses', 'spatial', 'abricot', 'semence', 'émigrée', 'rouille', 'refuser', 'avaient', 'renommé', 'désoler', 'relater', 'agneler', 'bouclée', 'bloqués', 'centrée', 'crisper', 'maillon', 'plongés', 'dériver', 'charmer', 'immoral', 'salarié', 'estrade', 'crédits', 'moqueur', 'globaux', 'étroite', 'établie', 'syllabe', 'laissez', 'battant', 'chaînon', 'adoucir', 'autocar', 'vautour', 'matelas', 'dorment', 'acidulé', 'restent', 'navires', 'éleveur', 'insisté', 'choisis', 'saturer', 'convier', 'orateur']

# mot de taille égale à 8
L8 = ['invitant', 'défenses', 'piétonne', 'archange', 'aménagée', 'faudrait', 'séparent', 'équinoxe', 'délaissé', 'réticent', 'retirent', 'auspices', 'publions', 'amateurs', 'pavillon', 'estropié', 'chez-soi', 'élaborer', 'aiguiser', 'répandue', 'atrocité', 'tisonner', 'sifflets', 'Mitchell', 'craintes', 'félicité', 'agrandir', 'formules', 'escorter', 'sentence', 'confiait', 'pelletée', 'claviers', 'raréfier', 'auditeur', 'allaient', 'souriant', 'emprunté', 'heurtent', 'aumônier', 'musiques', 'établies', 'aiguille', 'huitième', 'artistes', 'délation', 'regrette', 'éteindre', 'fabrique', 'baptiser', 'renforcé', 'désirant', 'jouaient', 'divertir', 'énumérer', 'méchants', 'traduira', 'penchent', 'dispense', 'carillon', 'ponction', 'récupère', 'effectué', 'esquisse', 'chômeurs', 'glacière', 'mensonge', 'humaines', 'approuve', 'localité', 'inspirée', 'empressé', 'financer', 'surannés', 'exploits', 'incluant', 'recteurs', 'créances', 'jointure', 'enserrer', 'croisent', 'requêtes', 'résulter', 'broderie', 'mondiaux', 'étroites', 'diplômes', 'imaginez', 'étudient', 'machines', 'éminence', 'roitelet', 'préférer', 'hôtelier', 'importés', 'agrément', 'effectue', 'hectares', 'patience', 'concours']

# mot de taille égale à 9
L9 = ['navigants', 'équilibré', 'intendant', 'collègues', 'instiguer', 'courgette', 'estaminet', 'réfléchit', 'auditeurs', 'abasourdi', 'empreinte', 'habitants', 'serviette', 'moniteurs', 'documents', 'carburant', 'pouvaient', 'idéologie', 'proposera', 'arabesque', 'affichage', 'notoriété', 'familière', 'Orientale', 'rachetant', 'ethniques', 'jardinier', 'savoureux', 'appartenu', 'munitions', 'rapproche', 'déterminé', 'émouvante', 'incendies', 'angoisses', 'abondance', 'actuelles', 'génétique', 'vociférer', 'adressées', 'déclivité', 'étreindre', 'commander', 'retrouvés', 'dispersés', 'récidiver', 'déception', 'inscrites', 'monopoles', 'cassettes', 'rattachée', 'prudentes', 'financées', 'médiation', 'conscient', 'couronnes', 'indiquait', 'renchérit', 'amplifier', 'échappent', 'préventif', 'ambitions', 'exubérant', 'saucisson', 'ambitieux', 'percevoir', 'rogatoire', 'embarqués', 'pollution', 'participe', 'précédent', 'recevront', 'batailles', 'populiste', 'précisait', 'remercier', 'sangloter', 'disposait', 'instances', 'symbolise', 'aquatique', 'partition', 'cependant', 'suggèrent', 'brutalité', 'chaotique', 'inférieur', 'personnes', 'politesse', 'atteindre', 'reproduit', 'fiscalité', 'pratiques', 'chandelle', 'étrangler', 'obscénité', 'prophètes', 'craignent', 'cherchant', 'renfrogné']

#mot de taille égale à 10
L10 = ['tourmenter', 'bananeraie', 'chambranle', 'arbrisseau', 'paradoxale', 'alcoolique', 'admirateur', 'consortium', 'impénitent', 'condamnant', 'difficiles', 'pressentir', 'orthodoxes', 'diététique', 'apparaître', 'athlétique', 'pluraliste', 'formidable', 'groupement', 'timidement', 'clairement', 'Pirandello', 'évaluation', 'antiquaire', 'réflexions', 'pétocharde', 'robustesse', 'marchepied', 'végétation', 'distinguer', 'commentant', 'fréquences', 'reprochait', 'allocation', 'acoustique', 'Manchester', 'perfection', 'permanents', 'rapidement', 'hurluberlu', 'anglophile', 'bombardier', 'herboriste', 'indéniable', 'interrompu', 'dégouliner', 'déterminée', 'symbolique', 'dilettante', 'vulnérable', 'malfaiteur', 'suicidaire', 'complexion', 'dissidents', 'carrefours', 'hésitation', 'secrétaire', 'pétroliers', 'déterminer', 'transports', 'autochtone', 'épargnants', 'expectorer', 'consistant', 'restreinte', 'apaisement', 'détestable', 'sanctuaire', 'étançonner', 'débouchant', 'interroger', 'prochaines', 'aspirateur', 'inhumanité', 'souveraine', 'quelconque', 'insouciant', 'placements', 'godelureau', 'métallique', 'solidement', 'divergence', 'fréquentés', 'entretenus', 'dérisoires', 'Mauritanie', 'courageuse', 'rassemblés', 'monstrueux', 'amputation', 'éventuelle', 'paragraphe', 'envisagent', 'astronomie', 'compliment', 'présentera', 'souhaitait', 'baïonnette', 'contrôlées', 'nécessaire']

# mot de taille > 10
L20 = ['micro-ordinateur', 'coopérations', 'propriétaires', 'paperassier', 'narcissisme', 'opportunément', 'socio-politique', 'châtaignier', 'constamment', 'généreusement', 'parlementaire', 'approvisionnement', 'différencier', 'pandémonium', 'anachronique', 'prédominance', 'assassinats', 'statistiques', 'complémentaire', 'admiratrice', 'rentabiliser', 'délinéament', 'révélatrice', 'non-valable', 'approbation', 'anticonstitutionnel', 'candidature', 'appréhender', 'électricité', 'aristocratie', 'adolescence', 'observations', 'probablement', 'instructions', 'injustement', 'monarchique', 'infractions', 'dignitaires', 'pouponnière', 'souhaitaient', 'électricien', 'fléchissement', 'unilatéralement', 'sournoiserie', 'écoeurement', 'théologiens', 'folklorique', 'compartiments', 'garantissant', 'illégalement', 'laboratoires', 'conservation', 'narcissique', 'mélancolique', 'représentations', 'radioactifs', 'recueillies', 'représentativité', 'modestement', 'inaccoutumé', 'interrogateur', 'infaillible', 'préliminaires', 'impérialisme', 'indignation', 'remboursement', 'républiques', 'accompagner', 'terriblement', 'automobiliste', 'malentendant', 'alternatives', 'distribuant', 'parvenaient', 'solennellement', 'syndicalisme', 'provocation', 'aboutissent', 'dégauchissement', 'occidentales', 'aquarelliste', 'hypothétique', 'inguérissable', 'malveillant', 'impératrice', 'provisionner', 'extérieures', 'architecture', 'invraisemblable', 'concrètement', 'spécialisation', 'inimaginable', 'anthropologie', 'tarification', 'apparaissait', 'effectivement', 'apoplectique', 'destinataire', 'désintéressé', 'communistes']
